### PR TITLE
V1.2 pre release

### PR DESCRIPTION
**Pull request by priyaayyar**

### CODE REVIEW

**Review by tbruno — CHANGES_REQUESTED** [review]
This PR should not be merged.

**Comment by dosten** [comment]
This should not be merged.

**Review by dosten — CHANGES_REQUESTED** [review]
This should not be merged.

**Comment by dosten** [comment]
Closing as should not be merged, @priyaayyar you can use this link to check the differences between v1.1 and v1.2: https://github.com/mulesoft/docs-service-mesh/compare/v1.1...v1.2

**Pull request closed without merging**
