### PR TITLE
[W-11995639] Document xAPI unsupported changes

### PR DESCRIPTION
**Pull request by NachoRaik**
This PR removes the sections mentioning the option of using user credentials.

### CODE REVIEW

**Review by glenn-rodgers-sf — CHANGES_REQUESTED** [review]
All the writing looks good. However, I would direct the user to how to setup the connected apps approach in the IMPORTANT note. If this would be clear to them and I just don't know because of my lack knowledge of the product, just let me know and I'll approve.

**Comment by NachoRaik** [comment]
Hi @glenn-rodgers-sf , just added what you suggested. Would it be ready to be merged?

**Comment by NachoRaik** [comment]
Hi @glenn-rodgers-sf , just added what you suggested. Would it be ready to be merged?

**Comment by NachoRaik** [comment]
Hi @glenn-rodgers-sf , just added what you suggested. Would it be ready to be merged?

**Review by glenn-rodgers-sf — APPROVED** [review]

**Review by priyaayyar — APPROVED** [review]

**Pull request merged**
